**Table of contents**<a id='toc0_'></a>    
- [Imports](#toc1_)    
- [Load data](#toc2_)    
- [Run PyCaret](#toc3_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[Imports](#toc0_)

In [2]:
import pickle

import pandas as pd

from pycaret.classification import *

from controller import Controller

In [3]:
c = Controller('i01')

# <a id='toc2_'></a>[Load data](#toc0_)

In [4]:
filepath = fr'{c.get_path_iteration()}/{c.iteration}_ss.pkl'
selection_set = pd.read_pickle(filepath)

In [5]:
filepath = fr'{c.get_path_data_prepared()}/01_df_train_val_test.pkl'
df_full = pd.read_pickle(filepath)
df_full = df_full[selection_set + ['EVENT_RISK']]
df_full = df_full.head(500)
df_full

,ACN_NUM_ACN,TIME_DATE,TIME_1_LOCAL_TIME_OF_DAY,PLACE_LOCALE_REFERENCE,PLACE_1_STATE_REFERENCE,PLACE_2_RELATIVE_POSITION_ANGLE_RADIAL,PLACE_3_RELATIVE_POSITION_DISTANCE_NAUTICAL_MILES,PLACE_4_ALTITUDE_AGL_SINGLE_VALUE,PLACE_5_ALTITUDE_MSL_SINGLE_VALUE,ENVIRONMENT_FLIGHT_CONDITIONS,...,EVENTS_3_DETECTOR,EVENTS_4_WHEN_DETECTED,ASSESSMENTS_CONTRIBUTING_FACTORS_SITUATIONS,ASSESSMENTS_1_PRIMARY_PROBLEM,REPORT_1_NARRATIVE,REPORT_1_1_CALLBACK,REPORT_2_NARRATIVE,REPORT_2_1_CALLBACK,REPORT_1_2_SYNOPSIS,EVENT_RISK
0,1574675,201808,0601-1200,SNA.Airport,CA,NaN,NaN,NaN,5000.0,NA,...,Person Air Traffic Control; Person Flight Crew,In-flight,Human Factors,Human Factors,SNA RNP-Z to Runway 20R. The FMC was properly ...,NA,We were cleared for the RNP RNAV Z 20R Approac...,NA,B737-700 flight crew reported failing to make ...,2
1,1224894,201412,0601-1200,MSY.Airport,LA,NaN,NaN,1000.0,NaN,VMC,...,Person Flight Crew,In-flight,Human Factors,Human Factors,On base to final turn to runway 1 in MSY at ap...,NA,NA,NA,Captain reports sighting of a drone at 1;000 f...,0
2,1134202,201312,1201-1800,ZZZ.ARTCC,US,NaN,NaN,NaN,2600.0,IMC,...,Person Flight Crew,In-flight,Human Factors; Aircraft; Procedure; Weather,Aircraft,I climbed to my filed altitude of 5;000 FT; an...,NA,NA,NA,SR22 pilot became disoriented on approach in I...,3
3,1222074,201411,1201-1800,CWA.Airport,WI,NaN,20.0,NaN,4000.0,NA,...,Person Flight Crew,In-flight,Aircraft,Aircraft,I had my pitot heat checked prior to winter an...,NA,NA,NA,BE58 pilot experiences pitot heat failure desc...,2
4,1733019,202003,1801-2400,ZDV.ARTCC,CO,NaN,NaN,NaN,32000.0,NA,...,Person Flight Crew,In-flight,Airspace Structure; Weather,Weather,At 32000 ft. just north of PUB the aircraft ex...,NA,NA,NA,B737 First Officer reported unexpected moderat...,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1701692,201911,1201-1800,TNCM.Airport,FO,NaN,NaN,0.0,NaN,VMC,...,Person Flight Crew,In-flight,Aircraft; Procedure,Aircraft,We have planned for a 27K MAX BUMP bleeds off ...,NA,NA,NA,B737 Captain reported a rejected takeoff after...,2
496,1183120,201406,1201-1800,ZZZ.Airport,US,NaN,5.0,NaN,2400.0,VMC,...,Person Flight Crew,In-flight,Aircraft,Aircraft,Shortly after takeoff (approximately 1800 feet...,The reporter states that the power loss occurr...,NA,NA,DHC8-100 Captain experiences a power loss afte...,4
497,1702661,201911,0601-1200,ZZZ.Airport,US,NaN,NaN,0.0,NaN,NA,...,Person Flight Crew,Taxi,Airport; Environment - Non Weather Related,Ambiguous,We were taxiing out for takeoff on Taxiway Alp...,NA,NA,NA,Flight Crew reported that as they taxied up to...,2
498,1825959,202107,0001-0600,EVV.Airport,IN,NaN,NaN,NaN,NaN,VMC,...,Automation Aircraft Terrain Warning; Person Fl...,NA,Human Factors,Human Factors,We were doing a late night flight to Evansvill...,NA,While hand flying the approach around 500 ft. ...,NA,Air carrier flight crew reported the pilot fly...,2
499,1437983,201704,0601-1200,ZZZ.Airport,US,NaN,NaN,1500.0,NaN,VMC,...,Automation Aircraft Terrain Warning; Person Fl...,In-flight,Human Factors; Weather,Human Factors,The crew and the aircraft were repositioning a...,NA,NA,NA,Global 5000 Captain reported continuing an app...,0

# <a id='toc3_'></a>[Run PyCaret](#toc0_)

In [7]:
text_features = [col for col in df_full.select_dtypes('object') if df_full[col].str.len().max() > 10]
text_features

['PLACE_LOCALE_REFERENCE',
 'ENVIRONMENT_1_WEATHER_ELEMENTS_VISIBILITY',
 'ENVIRONMENT_2_WORK_ENVIRONMENT_FACTOR',
 'AIRCRAFT_1_ATC_ADVISORY',
 'AIRCRAFT_1_1_AIRCRAFT_OPERATOR',
 'AIRCRAFT_1_2_MAKE_MODEL_NAME',
 'AIRCRAFT_1_7_MISSION',
 'AIRCRAFT_1_8_NAV_IN_USE',
 'AIRCRAFT_1_9_FLIGHT_PHASE',
 'AIRCRAFT_1_10_ROUTE_IN_USE',
 'AIRCRAFT_1_11_AIRSPACE',
 'AIRCRAFT_1_16_MAINTENANCE_STATUS_MAINTENANCE_TYPE',
 'AIRCRAFT_1_17_MAINTENANCE_STATUS_MAINTENANCE_ITEMS_INVOLVED',
 'COMPONENT_AIRCRAFT_COMPONENT',
 'COMPONENT_1_MANUFACTURER',
 'COMPONENT_3_PROBLEM',
 'AIRCRAFT_2_ATC_ADVISORY',
 'AIRCRAFT_2_1_AIRCRAFT_OPERATOR',
 'AIRCRAFT_2_2_MAKE_MODEL_NAME',
 'AIRCRAFT_2_8_NAV_IN_USE',
 'AIRCRAFT_2_9_FLIGHT_PHASE',
 'AIRCRAFT_2_10_ROUTE_IN_USE',
 'AIRCRAFT_2_11_AIRSPACE',
 'AIRCRAFT_2_31_FLYING_IN_NEAR_OVER_UAS_',
 'AIRCRAFT_2_34_NUMBER_OF_UAS_BEING_CONTROLLED_UAS_',
 'PERSON_1_LOCATION_OF_PERSON',
 'PERSON_1_1_LOCATION_IN_AIRCRAFT',
 'PERSON_1_2_REPORTER_ORGANIZATION',
 'PERSON_1_3_FUNCTION',
 'PERSON_1_4_QUALIFICATION',
 'PERSON_1_5_EXPERIENCE',
 'PERSON_1_6_CABIN_ACTIVITY',
 'PERSON_1_7_HUMAN_FACTORS',
 'PERSON_1_8_COMMUNICATION_BREAKDOWN',
 'PERSON_1_9_UAS_COMMUNICATION_BREAKDOWN',
 'PERSON_2_LOCATION_OF_PERSON',
 'PERSON_2_1_LOCATION_IN_AIRCRAFT',
 'PERSON_2_2_REPORTER_ORGANIZATION',
 'PERSON_2_3_FUNCTION',
 'PERSON_2_4_QUALIFICATION',
 'PERSON_2_5_EXPERIENCE',
 'PERSON_2_7_HUMAN_FACTORS',
 'PERSON_2_8_COMMUNICATION_BREAKDOWN',
 'EVENTS_ANOMALY',
 'EVENTS_1_MISS_DISTANCE',
 'EVENTS_3_DETECTOR',
 'EVENTS_4_WHEN_DETECTED',
 'ASSESSMENTS_CONTRIBUTING_FACTORS_SITUATIONS',
 'ASSESSMENTS_1_PRIMARY_PROBLEM',
 'REPORT_1_NARRATIVE',
 'REPORT_1_1_CALLBACK',
 'REPORT_2_NARRATIVE',
 'REPORT_2_1_CALLBACK',
 'REPORT_1_2_SYNOPSIS']

In [8]:
s1 = setup(data=df_full, text_features=text_features)

In [10]:
# compare baseline models
best = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .              10:52:09
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [11]:
pull()

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
catboost,CatBoost Classifier,0.4829,0.7088,0.4829,0.4870,0.4241,0.2520,0.2857,182.359
et,Extra Trees Classifier,0.4714,0.7111,0.4714,0.4615,0.3929,0.2209,0.2778,2.257
rf,Random Forest Classifier,0.4657,0.7075,0.4657,0.4400,0.3865,0.2088,0.2648,2.438
lightgbm,Light Gradient Boosting Machine,0.4571,0.6590,0.4571,0.4475,0.4060,0.2244,0.2501,3.341
xgboost,Extreme Gradient Boosting,0.4543,0.6704,0.4543,0.4463,0.4158,0.2330,0.2508,32.412
gbc,Gradient Boosting Classifier,0.4343,0.6608,0.4343,0.4130,0.3737,0.1880,0.2157,18.338
lda,Linear Discriminant Analysis,0.4086,0.6607,0.4086,0.3428,0.2962,0.0982,0.1625,3.598
ridge,Ridge Classifier,0.4029,0.0000,0.4029,0.3895,0.3783,0.2048,0.2117,1.645
dummy,Dummy Classifier,0.3686,0.5000,0.3686,0.1359,0.1986,0.0000,0.0000,2.013
lr,Logistic Regression,0.3657,0.5279,0.3657,0.1586,0.2076,0.0035,0.0038,21.581
ada,Ada Boost Classifier,0.3486,0.5799,0.3486,0.3159,0.2881,0.0661,0.0752,3.079
qda,Quadratic Discriminant Analysis,0.3371,0.5042,0.3371,0.2211,0.2355,0.0105,0.0075,3.304
dt,Decision Tree Classifier,0.3143,0.5222,0.3143,0.2995,0.2867,0.0543,0.0581,1.988
knn,K Neighbors Classifier,0.2657,0.4943,0.2657,0.2231,0.2374,0.0051,0.0058,4.905
svm,SVM - Linear Kernel,0.2514,0.0000,0.2514,0.1002,0.1224,0.0284,0.0358,2.416
nb,Naive Bayes,0.2057,0.5672,0.2057,0.2423,0.1478,0.0584,0.0751,2.584